version: "3"

services:
  pad:
    image: pad
    container_name: pad
    volumes:
      - ./images:/app/images
      - ./config.yaml:/app/config.yaml
      - ./token:/app/.token

networks:
  default:
